services:
  - type: web
    name: my-comp-bot
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm ci --omit=dev
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: PRICE_FILE
        value: ./Price of Age Computers.xlsx
      - key: WEBHOOK_URL
        sync: false
      - key: NODE_ENV
        value: production
